"""Resample a g1-moves motion npz to the tracking environment's policy rate.

mjlab's MotionLoader never reads the `fps` key: it consumes one frame per policy
step and assumes the file is already at that rate. The g1-moves clips are 60 fps
and the tracking env runs at 50 Hz, so playing one as-is stretches the motion by
1.2x and leaves the stored velocities inconsistent with the positions actually
being tracked.

Follows mjlab's own csv_to_npz convention: lerp positions and joint angles, slerp
orientations, then central-difference every velocity. A cubic-spline derivative
looks more principled and inflates peak joint velocity 16.8 -> 26.5 rad/s,
because the source velocities are themselves smoothed central differences.

Body positions and orientations are regenerated by forward kinematics from the
interpolated root pose and joint angles, not interpolated directly, so the file
stays exactly kinematically consistent the way csv_to_npz's does.

    python prep_motion.py IN.npz OUT.npz --output-fps 50
"""

import argparse
from pathlib import Path

import mujoco
import numpy as np
from scipy.spatial.transform import Rotation, Slerp


def _wxyz_to_xyzw(q):
    return np.concatenate([q[..., 1:], q[..., :1]], axis=-1)


def _xyzw_to_wxyz(q):
    return np.concatenate([q[..., 3:], q[..., :3]], axis=-1)


def _canonicalise(q):
    """q and -q are the same rotation but a sign flip breaks slerp."""
    q = q.copy()
    flip = np.cumprod(np.where(np.sum(q[1:] * q[:-1], axis=-1) < 0.0, -1.0, 1.0))
    q[1:] *= flip[:, None]
    return q


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.strip().split("\n")[0])
    ap.add_argument("src", type=Path)
    ap.add_argument("dst", type=Path)
    ap.add_argument("--output-fps", type=float, default=50.0)
    args = ap.parse_args()

    from mjlab.asset_zoo.robots import get_g1_robot_cfg

    model = get_g1_robot_cfg().spec_fn().compile()
    data = mujoco.MjData(model)
    n_body = model.nbody - 1          # drop `world`

    z = np.load(args.src)
    fps_in = float(z["fps"][0])
    qp, bp, bq = z["joint_pos"], z["body_pos_w"], z["body_quat_w"]
    if qp.shape[1] + 7 != model.nq:
        raise SystemExit(f"motion has {qp.shape[1]} joints, model nq={model.nq}")
    if bp.shape[1] != n_body:
        raise SystemExit(f"motion has {bp.shape[1]} bodies, model has {n_body}")

    n_in = qp.shape[0]
    duration = (n_in - 1) / fps_in
    t_in = np.arange(n_in) / fps_in
    n_out = int(np.floor(duration * args.output_fps)) + 1
    t_out = np.arange(n_out) / args.output_fps
    dt_out = 1.0 / args.output_fps

    idx = np.clip(np.searchsorted(t_in, t_out, side="right") - 1, 0, n_in - 2)
    w = (t_out - t_in[idx]) / (t_in[idx + 1] - t_in[idx])

    def lerp(a):
        ww = w.reshape((-1,) + (1,) * (a.ndim - 1))
        return a[idx] * (1.0 - ww) + a[idx + 1] * ww

    joint_pos = lerp(qp.astype(np.float64))
    root_pos = lerp(bp[:, 0].astype(np.float64))
    root_rot = Slerp(t_in, Rotation.from_quat(
        _wxyz_to_xyzw(_canonicalise(bq[:, 0].astype(np.float64)))))(t_out)
    root_quat = _xyzw_to_wxyz(root_rot.as_quat())

    # forward kinematics, so bodies are consistent with the interpolated pose
    body_pos_w = np.empty((n_out, n_body, 3))
    body_quat_w = np.empty((n_out, n_body, 4))
    for t in range(n_out):
        data.qpos[0:3] = root_pos[t]
        data.qpos[3:7] = root_quat[t]
        data.qpos[7:] = joint_pos[t]
        mujoco.mj_forward(model, data)
        body_pos_w[t] = data.xpos[1:]
        body_quat_w[t] = data.xquat[1:]

    joint_vel = np.gradient(joint_pos, dt_out, axis=0)
    body_lin_vel_w = np.gradient(body_pos_w, dt_out, axis=0)

    body_ang_vel_w = np.empty((n_out, n_body, 3))
    for b in range(n_body):
        rot = Rotation.from_quat(_wxyz_to_xyzw(_canonicalise(body_quat_w[:, b])))
        rel = (rot[1:] * rot[:-1].inv()).as_rotvec() / dt_out
        body_ang_vel_w[0, b] = rel[0]
        body_ang_vel_w[-1, b] = rel[-1]
        body_ang_vel_w[1:-1, b] = 0.5 * (rel[:-1] + rel[1:])

    args.dst.parent.mkdir(parents=True, exist_ok=True)
    np.savez(
        args.dst,
        fps=np.array([args.output_fps]),
        joint_pos=joint_pos.astype(np.float32),
        joint_vel=joint_vel.astype(np.float32),
        body_pos_w=body_pos_w.astype(np.float32),
        body_quat_w=body_quat_w.astype(np.float32),
        body_lin_vel_w=body_lin_vel_w.astype(np.float32),
        body_ang_vel_w=body_ang_vel_w.astype(np.float32),
    )

    fd = np.gradient(joint_pos, dt_out, axis=0)
    rel_err = np.linalg.norm(joint_vel - fd) / np.linalg.norm(joint_vel)
    fk_err = 0.0
    for t in range(0, n_out, max(1, n_out // 40)):
        data.qpos[0:3] = body_pos_w[t, 0]
        data.qpos[3:7] = body_quat_w[t, 0]
        data.qpos[7:] = joint_pos[t]
        mujoco.mj_forward(model, data)
        fk_err = max(fk_err, np.abs(data.xpos[1:] - body_pos_w[t]).max())
    print(f"in  {args.src.name}: {n_in} frames @ {fps_in:g} fps  ({duration:.2f} s)")
    print(f"out {args.dst.name}: {n_out} frames @ {args.output_fps:g} fps  "
          f"({(n_out - 1) / args.output_fps:.2f} s)")
    print(f"  joint_vel vs d(joint_pos)/dt   {rel_err * 100:.2f} %")
    print(f"  forward-kinematics consistency {fk_err * 1000:.4f} mm")
    print(f"  peak |joint_vel| {np.abs(joint_vel).max():.2f} rad/s "
          f"(input {np.abs(z['joint_vel']).max():.2f})")
    print(f"  root height {body_pos_w[:, 0, 2].min():.3f} .. "
          f"{body_pos_w[:, 0, 2].max():.3f} m")


if __name__ == "__main__":
    main()
